In [ ]:
#지도학습(정답 존재o)
#회귀모델(1~100, 1000 등 키 가격 예측(연속적 값))
#분류모델개, 고양이, 사자 등)
#회귀모델 종류들 (선형회귀, 다항회귀, 릿지, 라쏘 등)-릿지와 라쏘는 선형회귀의 정규화 

In [ ]:
#선형회귀(종속변수(예측할 변수)와 하나 이상의 독립변수(예측하기 위해서 사용하는 변수)의 선형 관계(종속 변수와 독립변수의 관계가 단순히 덧셈 혹은 곱셈으로만 이루어진 관계-직선으로 표현 가능해야함)를 모델링하는 방법)
#단순 선형회귀(독립변수가 하나인 경우)
#다중 선형회귀(독립변수가 여러개인 경우)
#학습 : 가중치(파라미터)를 찾는 과정(키 = b0 + b1*나이 라는 식에서 b0와 b1을 찾는 과정)-목적함수(손실함수)를 최소화하면서 점점 가중치를 찾는 과정(=오차가 적어질 수 있도록)
#목적함수 : 손실함수(평균제곱오차(MSE), 평균절대오차(MAE) 등)를 최소화하는 가중치를 찾는 것이 목적-에측한 키와 실제 키와 차이를 최소화하는 가중치를 찾는 것이 목적
#경사 하강법: 목적함수를 최소화하는 가중치를 찾기 위해서 
#가중치가 업데이트 될 때마다 최적점에 갈수도 지역점에 갈수도 있음


In [1]:
import numpy as np #연산을 위한
import pandas as pd #데이터 처리를 위한
from sklearn.model_selection import train_test_split #데이터 분할을 해주는 모델
from sklearn.linear_model import LinearRegression #선형회귀 모델
from sklearn.metrics import mean_squared_error, r2_scor #성능 평가를 위한 모델-예측값과 실제값을 어떻게 찾을지
#metrics : 성능평가를 위한 모듈

In [2]:
#데이터 생성
X = np.array([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5],[6,6]])#독립변수(특징=입력값)
y = np.array([1, 2, 3, 4, 5, 6])#종속변수(레이블=정답=출력값)

In [3]:
# 데이터 분할 (훈련 데이터와 테스트 데이터)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#X_train, X_test 순서가 바뀌면 다른 데이터가 들어감
#train_test_split : 데이터를 훈련용과 테스트용으로 나눠주는 함수 test_size=0.2 : 20%를 테스트용으로 나눠줌, random_state=42 : 랜덤으로
#y_train, y_test로 나누는 이유: 모의고사 시럼 정답과 실제 시험 정답으로 나누어야 과적합을 방지할 수 있음, 일반화를 위해서

In [5]:
# 선형 회귀 모델 생성 및 학습
model = LinearRegression() #선형회귀 모델 생성(이렇게 모델들의 fit 메서드는 입력값과 출력값을 모두 활용하여 가중치를 찾음)
model.fit(X_train, y_train) #학습

LinearRegression()

In [7]:
# 예측
y_pred = model.predict(X_test)
y_pred
X_test

array([[1, 1],
       [2, 2]])

In [8]:
# 모델 평가
mse = mean_squared_error(y_test, y_pred) #mse : 0에 가까울수록 좋다
r2 = r2_score(y_test, y_pred) #r2 : 1에 가까울수록 좋다
#모델 평가는 이유: 1. 모델이 얼마나 잘 예측하는지 알아야함 2. 모델이 새로운 데이터에서도 잘 작동하는지 확인 3. 모델을 비교하고 선택해야 함(다른 적합한 모델들이 있을 수 있음) 4. 데이터 품질과 모델 한게를 이해해야함(모델이 잘못된 이유를 알아야함)
print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

In [9]:
X_test_7 = np.array([[7, 7]]) #예측할 데이터(원래 7이 없는데 넣어봄)
model.predict(X_test_7) #예측

array([7.])

In [ ]:
#다항회귀종속 변수와 독립 젼수 간의 비선형 관계를 모델링하는 방법)
#종속변수를 단순히 1차방정식으로만 표현해서 예측하기 어려운 것은 다항방정식으로 표현하면 예측하기 쉬워짐
#족절한 차수 선택 : 차수가 너무 낮으면 다른거 예측을 못함, 차수가 너무 높으면 복잡해지고 과적합이 일어날 수 있음

In [10]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures #데이터 전처리(입력 특성(독립변수)을 바탕으로 다항 항들(새로운 특성들)을 새롭게 만들어줌)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [11]:
# 데이터 생성
X = np.array([[1], [2], [3], [4], [5], [6]])
y = np.array([1, 4, 9, 16, 25, 36])

In [12]:
# 다항 특징 생성 (차수 2)
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X) #X(독립변수)만 필요 o, y(종속변수)는 필요 x
#fit : 학습만 시키는 것, transform : 변환만 시키는 것, fit_transform : 학습과 변환을 동시에 시키는 것
#변환 : 학습한 값을 이용하여 실제 데이터를 변환하는 것

In [13]:
# 데이터 분할 (훈련 데이터와 테스트 데이터)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size=0.2, random_state=42)

In [14]:
X_poly

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.],
       [ 1.,  5., 25.],
       [ 1.,  6., 36.]])

In [15]:
# 다항 회귀 모델 생성 및 학습
model = LinearRegression() #선형회귀 모델을 생성하기 전에 이미 다항식을 만들어주었기 때문에 다항회귀 모델이 됨
model.fit(X_train, y_train)

LinearRegression()

In [16]:
# 예측
y_pred = model.predict(X_test)

In [17]:
# 모델 평가
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

Mean Squared Error: 1.9721522630525295e-29
R^2 Score: 1.0
